### ISSUE TITLE
Error while loading FMI3 FMU

### ISSUE THREAD

**Issue by Sov-trotter** [ThummeTo/FMIImport.jl#9]
While trying to load an fmu get the following error

```julia
ERROR: UndefVarError: fmi3ProvidesDirectionalDerivatives not defined
Stacktrace:
 [1] fmi3Load(pathToFMU::String; unpackPath::Nothing)
   @ FMIImport ~/.julia/packages/FMIImport/jYeff/src/FMI3_ext.jl:161
 [2] fmi3Load(pathToFMU::String)
   @ FMIImport ~/.julia/packages/FMIImport/jYeff/src/FMI3_ext.jl:20
 [3] top-level scope
   @ REPL[2]:1
```

It seems a typo [here](https://github.com/ThummeTo/FMIImport.jl/blob/d8cc4412354943895edc8008defb9b0354e71b79/src/FMI3_fmu_to_md.jl#L37-L39)

**Comment by ThummeTo** [comment]
Dear @Sov-trotter ,
thanks for the issue. We are currently working on refactoring the FMI3-Code to match the new FMI.jl topology (in fact, there are much more issues than just that typo). I hope that we can provide an update next week at the latest.
Regards!

**Comment by Sov-trotter** [comment]
Sure. I have been experimenting around abit and can conclude the same. Do let me know when you're open for any PR's. Thanks
